spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dongnaejogak_db?serverTimezone=Asia/Seoul
    username: root
    password: gudwns11!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true