spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500

  security:
    oauth2:
      provider:
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          client-name: Naver
          redirect-uri: https://dongnaejogak.kro.kr/login/oauth2/code/naver
          authorization-grant-type: authorization_code
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response

        google:
          client-id:
          client-secret:

jwt:
  secret: ${JWT_SECRET}
  time:
    access: 3600000      # 1 hour (ms)
    refresh: 2592000000  # 30 days (ms)
